/* eslint-disable global-require */
module.exports = {
  ...require('./checkNetworkConnection'),
  ...require('./getNewWalletInfo'),
  ...require('./identity/registerIdentity'),
  ...require('./identity/retrieveIdentity'),
  ...require('./identity/topupIdentity'),
  ...require('./identity/updateIdentityAddKey'),
  ...require('./identity/updateIdentityDisableKey'),
  ...require('./identity/retrieveAccountIdentityIds'),
  ...require('./identity/transferCredits'),
  ...require('./identity/withdrawCredits'),
  ...require('./name/registerName'),
  ...require('./name/registerAlias'),
  ...require('./name/retrieveNameByName'),
  ...require('./name/retrieveNameByRecord'),
  ...require('./name/retrieveNameBySearch'),
  ...require('./contract/registerContractProvided'),
  ...require('./contract/updateContractProvided'),
  ...require('./contract/retrieveContract'),
  ...require('./document/submitDocument'),
  ...require('./document/getDocument'),
  ...require('./document/updateDocument'),
  ...require('./document/deleteDocument'),
  ...require('./sendFunds'),
  ...require('./dapiClientMethods'),
};
